name: backend

on:
  push:
    branches:
      - main
      - aoc-infra # todo: remove after test
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
      - '.github/workflows/build-backend.yml'
      - '.github/workflows/publish.yml'

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set-tag.outputs.tag }}
    steps:
      - id: set-tag
        run: echo "tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

  run-build:
    needs:
      - version
    uses: ./.github/workflows/build-backend.yml
    with:
      tag: ${{ needs.version.outputs.tag }}

  publish:
    needs:
     - version
     - run-build

    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    uses: ./.github/workflows/publish.yml
    with:
      tag: ${{ needs.version.outputs.tag }}
      artifact-name: backend-jar
      artifact-path: backend/build/libs/
      image-name: backend
      docker-context: ./backend
