name: backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
      - '.github/workflows/build-backend.yml'
env:
  REGISTRY: ghcr.io

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set-tag.outputs.tag }}
    steps:
      - id: set-tag
        run: echo "tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

  run-build:
    needs:
      - version
    uses: ./.github/workflows/build-backend.yml
    with:
      tag: ${{ needs.version.outputs.tag }}

  publish:
    needs:
     - version
     - run-build
    uses: ./.github/workflows/publish.yml
    with:
      tag: ${{ needs.version.outputs.tag }}
      artifact-name: backend-jar
      artifact-path: backend/build/libs/
      image-name: backend
      docker-context: ./backend
