name: frontend

on:
  workflow_call:

jobs:
  version:
    uses: ./.github/workflows/version.yml
    with:
      service-name: frontend

  run-build:
    needs:
      - version
    uses: ./.github/workflows/build-frontend.yml
    with:
      version: ${{ needs.version.outputs.version }}

  publish:
    needs:
      - version
      - run-build

    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    uses: ./.github/workflows/publish.yml
    with:
      version: ${{ needs.version.outputs.version }}
      artifact-name: frontend-dist
      artifact-path: frontend/dist/
      image-name: frontend
      docker-context: ./frontend
