name: verify

on:
  push:
    branches-ignore:
      - main

jobs:
  backend:
    uses: ./.github/workflows/build-backend.yml
    with:
      tag: "temp-tag"

  frontend:
    uses: ./.github/workflows/build-frontend.yml
    with:
      tag: "temp-tag"
