name: pipeline
on:
  push:
    branches-ignore:
      - main

jobs:
  build-backend:
    uses: ./.github/workflows/build-backend.yml
    with:
      tag: "temp-tag"

  build-frontend:
    uses: ./.github/workflows/build-frontend.yml
    with:
      tag: "temp-tag"
